### ISSUE TITLE
Not locating js-controller

### ISSUE THREAD

**Issue by Disillusioned** [Apollon77/ioBroker.mbus#14]
Hi i recently downloaded the zip file of this and ran npm i, and it builded successfully.

When i try 'node main.js" it gives me the error 'Cannot find js-controller'/.
Also noticed inside of the /admin folder the index and index_m files don't display correctly as they're 
missing a couple js & css files.

![image](https://user-images.githubusercontent.com/41115272/42638281-1995d120-85e5-11e8-8941-3527913c2850.png)

How can I fix this?

**Comment by Apollon77** [comment]
What you did? This is a plugin for the homeautomation system iobroker. SO you need to have iobroker installed first and then add this as adapter/plugin there.

It is NOT a standalone program.

If you want a library for nodejs try node-mbus

**Comment by Disillusioned** [comment]
I see! Sorry about that I wasn't aware.
Is there any way to change the baud rate for TCP in node-mbus?

**Comment by Apollon77** [comment]
When you use a TCP mbus Master then this one is handling the serial stuff, so this TCP mbus master device needs to have a setting for it.
