### ISSUE TITLE
Current Unrecognized VIF extension: 0x3a - B+G Tech SDM 630 V2

### ISSUE THREAD

**Issue by Habedere** [Apollon77/ioBroker.mbus#144]
Hallo,
ich möchte aktuell o.g. Zähler "SDM 630" auslesen.
Der Adapter findet die Zähler und erstellte auch Objekte.
Allerdings kann ich nicht alle Werte auslesen.
Bei einigen steht wie folgt:
Name "Current Unrecognized VIF extension: 0x3a"
Wert "11296 Unrecognized VIF extension: 0x3a"

![SDM630_kpl](https://user-images.githubusercontent.com/43848202/95896262-463e4280-0d8c-11eb-8d2b-df412bc6ff15.PNG)

Eine Idee woran es liegen könnte?
Google meint evtl. sind mehr Daten auszulesen wenn man über die Sekundäradresse ausliest. Macht das Sinn?
Kann ich hier etwas umstellen?

**Comment by Apollon77** [comment]
AM ENde wäre das ein isue für libmbus weil der Adapter auf dieser nativen Library basiert und das ganze Parsing des protokolls dort passiert.  ALso wäre ein issue hier https://github.com/rscada/libmbus sinnvoll. Ich kann das aktuell wenig tun, ausser warten das es dort bearbeitet wurde. Bin im C++ code nicht wirklich drin
