### ISSUE TITLE
No connection over TCP/IP to Moxa NPort

### ISSUE THREAD

**Issue by andiling** [Apollon77/ioBroker.mbus#16]
Hi, i like to communicate over a Moxa NPort IP-Serial converter with my serial M-Bus Gateway!
In a early version it has worked! Then the update an no connection possible! Have you any idea?

**Comment by Apollon77** [comment]
Which version worked? Which no longer? More details please!!
Please try to set higher tcp timeout values. The defauls were lowered a bit compared to earlier versions

**Comment by andiling** [comment]
Hi, ich schreibe jetzt in Deutsch weiter! Ich kann es ehrlich gesagt nicht genau sagen welche Version funktioniert hat! Ich hatte damals gesehen dass ein neuer Adapter names M-Bus verfügbar ist und habe mit diesem erfolgreich den Stromzähler lesen können. Dann kam das Update und jetzt baut er nicht mal eine TCP Verbindung auf zum Moxa! System ist ein Intel Core I5 NUC mit 16GB RAM und Debian Jessie als Betriebssystem. Node.js ist 6.14.3. Ich schreibe gerade an einem Adapter der mit dem Moxa Modem und einer Heliotherm Wärmepumpe kommuniziert und dort mache ich das ohne node serialport. Das Modem hat zwar seine Tücken aber damit könnte ich leben. 

Ich hätte noch eine Bitte! Ich fange gerade erst mit Javascript an und hab das mit den States anlegen und den Objects nocht nicht ganz kapiert! Könnte man mir das mal erklären?

**Comment by Apollon77** [comment]
Der MBus adapter ist schon ewig niht mehr aktualisiert worden. Kann es sein das DU noch z.B., nodejs aktualisiert hast? Dann musst Du native erweiterungen neu kompilieren - wie beim mbus adapter! Da musst Du ein "npm rebuild" ausführen.

Auch allgemein Log wäre super.

Wenn es das nicht ist dann bitte den adapter mit "npm install iobroker-mbus --debug" installieren und dann Debug-Loglevel aktivieren. Dann Log bitte senden. Da sollte man ggf mehr sehen.

Anderes Thema: Schreib am besten im ioBroker Entwickler Unterforum und Du bekommst Hilfe

**Comment by andiling** [comment]
Also, habe gestern eine komplkett neue installation von IOBroker gemacht auf nem anderen System! Neueste Node8 und NMP Version! Dort ist das selbe Problem! Keine Verbindung zum Modem!

Hier habe ich es mit nem kurzen Script versucht und da geht es komischerweise!
![m-bus script](https://user-images.githubusercontent.com/20771598/49034505-77babe80-f1b2-11e8-9d29-91b597bf6fa0.png)

**Comment by Apollon77** [comment]
Interesting. Can you please provide a debug log from the normal adapter?

**Comment by andiling** [comment]
The log allways says:


mbus.0 | 2018-11-26 21:48:57.168 | error | M-Bus Connection failed. Please check configuration.
-- | -- | -- | --
mbus.0 | 2018-11-26 21:48:57.168 | error | Error: No connection possible to MBus Host 172.16.15.5:4001
mbus.0 | 2018-11-26 21:48:57.067 | info | Initialize M-Bus TCP to 172.16.15.5:4001 with timeout 1500
mbus.0 | 2018-11-26 21:48:57.067 | info | Default Update Interval: 3600
mbus.0 | 2018-11-26 21:48:57.066 | info | starting. Version 0.1.8 in /opt/iobroker/node_modules/iobroker.mbus, node: v6.14.4

[Debug M-Bus.txt](https://github.com/Apollon77/ioBroker.mbus/files/2617297/Debug.M-Bus.txt)

**Comment by Apollon77** [comment]
Sorry, but no debug in there! Enable debug at "Instances" -> Expert mode -> Column Log-Stufe/Log Level set to debug

**Comment by andiling** [comment]
it is enabled

**Comment by andiling** [comment]
mbus.0 | 2018-11-26 22:00:38.827 | debug | system.adapter.admin.0: logging true
-- | -- | -- | --
mbus.0 | 2018-11-26 22:00:38.826 | debug | system.adapter.admin.0: logging true
mbus.0 | 2018-11-26 22:00:38.826 | debug | system.adapter.admin.0: logging true
mbus.0 | 2018-11-26 21:59:58.439 | debug | connected set to false
mbus.0 | 2018-11-26 21:59:58.435 | debug | connected set to false
mbus.0 | 2018-11-26 21:59:58.435 | debug | connected set to false
mbus.0 | 2018-11-26 21:59:58.433 | error | M-Bus Connection failed. Please check configuration.
mbus.0 | 2018-11-26 21:59:58.433 | error | Error: No connection possible to MBus Host 172.16.15.5:4001
mbus.0 | 2018-11-26 21:59:58.334 | info | Initialize M-Bus TCP to 172.16.15.5:4001 with timeout 1500
mbus.0 | 2018-11-26 21:59:58.333 | info | Default Update Interval: 3600
mbus.0 | 2018-11-26 21:59:58.333 | info | starting. Version 0.1.8 in /opt/iobroker/node_modules/iobroker.mbus, node: v6.14.4
mbus.0 | 2018-11-26 21:59:58.331 | debug | Update request for device 110053932E191302 already queued, so ignore update request
mbus.0 | 2018-11-26 21:59:58.331 | info | Schedule initialization for M-Bus-ID 110053932E191302 with update interval 3600
mbus.0 | 2018-11-26 21:59:58.331 | debug | Update request for device 1 already queued, so ignore update request
mbus.0 | 2018-11-26 21:59:58.331 | info | Schedule initialization for M-Bus-ID 1 with update interval 3600
mbus.0 | 2018-11-26 21:59:58.328 | info | Initialize M-Bus TCP to 172.16.15.5:4001 with timeout 1500
mbus.0 | 2018-11-26 21:59:58.328 | info | Default Update Interval: 3600
mbus.0 | 2018-11-26 21:59:58.326 | info | starting. Version 0.1.8 in /opt/iobroker/node_modules/iobroker.mbus, node: v6.14.4
mbus.0 | 2018-11-26 21:59:58.314 | debug | statesDB connected
mbus.0 | 2018-11-26 21:59:58.309 | debug | statesDB connected
mbus.0 | 2018-11-26 21:59:57.907 | warn | Reconnection to DB.
mbus.0 | 2018-11-26 21:59:57.898 | warn | Reconnection to DB.

**Comment by andiling** [comment]
Mir ist noch folgendes aufgefallen.
Der Adapter lässt sich nicht mehr über den Admin beenden! 
Es kommen auch keine Debug Ausgaben. 

Das Modem reagiert mit 90%iger Wahrscheinlich nicht wenn ich den Adapter starte.

Bisher hab ich es ein mal geschafft dass der Adapter für ca 10 Minuten gelaufen ist dann nicht mehr.

Ich kann nur noch mit dem kill Befehl in der Kommandozeile die Instanz beenden.

Ich habe leider keine Ahnung mehr was ich noch testen soll.

Irgend einen Tip oder eine idee?

**Comment by Apollon77** [comment]
Ich muss Zeit finden reinzuschauen. Ich habe halt kein tcp device von daher kann ich nur auf Verdacht arbeiten.

**Comment by andiling** [comment]
Ok, verstehe! Sag bescheid wie ich Dir irgendwie helfen kann bei der Analyse! Wireshark...etc. Programmieren kann ich schon aber leider bin ich im Javascript erst Anfänger (Ist Neuland für mich)! Aber ich lerne!

**Comment by Apollon77** [comment]
Mit deinen Infos kann ich mal Basis checken. Dann sehen wir weiter.

**Comment by Apollon77** [comment]
Pleas etry higher timeoutvalud of e.g. 5000 (5s)

**Comment by andiling** [comment]
Newest version is working yet! It was a timing problem!
