### ISSUE TITLE
Error 'Cannot find js-controller'

### ISSUE THREAD

**Issue by thomasstaltner** [Apollon77/ioBroker.mbus#164]
Out of the box, the dependency for js-controller ("iobroker.js-controller": "...") is not listed in the dependencies in package.json

After adding it manually, it seems to start correctly

Keep on the good work :-)

![image](https://user-images.githubusercontent.com/72125718/109950356-b5d1b180-7cdc-11eb-92d0-385348df34ca.png)

**Comment by Apollon77** [comment]
ääähhmm ... wht you did? This is a plugin for ioBroker, so ioBroker (and so js.controlelr) needs to be installed BEFORE adding this adapter ... so ... did you tried to install that "stand alone"?
