### ISSUE TITLE
Missing registers?

### ISSUE THREAD

**Issue by ttjaden** [Apollon77/ioBroker.mbus#165]
First of all: Thanks for the great plugin! But I have one question...

**Setting:**

- ioBroker as Docker ony Synology NAS 218+
- "Relay M-Bus Master" as serial converter
- 7 heating meters "Zelsius C5"

For the infomation sent by the Zelsius C5, please see: 
[Wärmemengenzähler_Zelsius-C5-ISF_M-Bus-Liste.pdf](https://github.com/Apollon77/ioBroker.mbus/files/6091839/Warmemengenzahler_Zelsius-C5-ISF_M-Bus-Liste.pdf)

**What I want:**
Monitoring several values into influx db
```
MWH | Actual heating energy
TF | Flow temperature
TR | Return temperature
QMPH | Actual flow rate
kW | Actual power
OpHours | Opterating hours
```

**Problem**
I can't find these values in ioBroker. I see all my 7 meters and a valid connection
![grafik](https://user-images.githubusercontent.com/16917049/110145843-25799680-7dda-11eb-97d0-600c4b304cfb.png)

But in the list of values I see
![grafik](https://user-images.githubusercontent.com/16917049/110145988-522dae00-7dda-11eb-8661-0d29e876d23a.png)
![grafik](https://user-images.githubusercontent.com/16917049/110146093-7093a980-7dda-11eb-9715-3197e79b371b.png)
![grafik](https://user-images.githubusercontent.com/16917049/110146172-899c5a80-7dda-11eb-8d54-a51bab009d8f.png)
![grafik](https://user-images.githubusercontent.com/16917049/110146228-9de05780-7dda-11eb-809b-50d4e18ed3e4.png)

Where do I find the values that I want to monitor?

**Comment by Apollon77** [comment]
What values you want to monitor? This is what the device returns via mbus ... try to use an alternaive software or libmbus to verify it. The adapter only can output what came back. If you want to see ore "core values" turn the adapter into debug log and check the output

**Comment by ttjaden** [comment]
Hi @Apollon77 
As i wrote above, I want, for example, monitor the flow and return temperature TF and TR see the following table with available values over m-bus
![grafik](https://user-images.githubusercontent.com/16917049/110158292-7644bb80-7de9-11eb-9727-033869f345ae.png)

Before I connected the Zelsius C5 with its Relay M-Bus Master to ioBroker it was running on a commercial logger. There I could get the values for Temperature and Power etc etc. So basically the must be there :-)

I now turned the adapter into debug mode, see the attached file. There i cannot find some kind of
[Uploading mbus.log…]()
 temperature °C ....

**Comment by ttjaden** [comment]
I found a person with the same issue as me! Please have a look at this issue in the libmbus-repository:
https://github.com/rscada/libmbus/issues/180
Solution would be:
- At first start, do `mbus-serial-request-data-multi-reply -b 2400 /dev/ttyUSB0` (for each id, I guess?)
- And afterwards for all following request: `mbus-serial-request-data -b 2400 /dev/ttyUSB0`

What do you think? Could you implement this?
I guess this PR deals with the same issue:
https://github.com/rscada/libmbus/pull/95

**Comment by Apollon77** [comment]
> Could you implement this?

I think we need to wait for a fix in libmbus - or at least until more details are known about the "why"

**Comment by Apollon77** [comment]
aahh now I understood it ... lets see what I can do

**Comment by Apollon77** [comment]
Ok, then try Github version please. you need to manually restart the adapter after that. how is it then?

**Comment by ttjaden** [comment]
Thanks @Apollon77  for your fast adjustment! I tested the new code with the following settings:
![grafik](https://user-images.githubusercontent.com/16917049/110237981-3d1e5f80-7f3f-11eb-9fe5-6378ee562be2.png)
![grafik](https://user-images.githubusercontent.com/16917049/110237993-49a2b800-7f3f-11eb-887a-45a67c0468c1.png)
Now the needed values are available, see
![grafik](https://user-images.githubusercontent.com/16917049/110238019-6ccd6780-7f3f-11eb-845c-9234f139a83b.png)
with power and temperature etc. Only one information: The value in the for energy (24442) is correct. But instead of "Wh" it is "kWh". The display shows 24,442 MWh, so that the value 24442 for kWh would be correct and only the wrong unit is shown.

I startet to log to influx every 60s to give it a test. And yes: it works now for the last 30min!
![grafik](https://user-images.githubusercontent.com/16917049/110238070-b453f380-7f3f-11eb-90df-5bf5ea0bff34.png)

**Comment by Apollon77** [comment]
Ok, for the unit: please provide a debug log to see what comes back, but most likely this is then a real issue from the libmbus where I can not do anything that fast (or the device returns invalit unit data).

**Comment by ttjaden** [comment]
For the unit: must have been some kind of glitch/bug. After a restart of the adapter, all is fine!
