### ISSUE TITLE
Feature Request: Eastron-SDM-Serie: instantaneous electrical information

### ISSUE THREAD

**Issue by Xander0823** [Apollon77/ioBroker.mbus#282]
Hallo,

ich nutze Elektrozähler der SDM-Serie des chinesischen Herstellers EASTRON.
Diese Slaves haben die Eigenschaft, bei Standardabfragen nur den Zählerwert zurückzuliefern.
Die ebenfalls vorhandenen Momentanwerte (Spannung, Strom, Leistung, Frequenz, etc) sind im Antworttelegram nicht vorhanden.

Um die Werte zu bekommen, muss die Abfrage wie in der angehängten Protokoll-Doku Kapitel 6.1 aussehen:
![grafik](https://user-images.githubusercontent.com/90933310/182037462-a78b31f2-e747-4787-b052-35fcabf96b88.png)

[SDM630-Mbus-protocol.pdf](https://github.com/Apollon77/ioBroker.mbus/files/9229333/SDM630-Mbus-protocol.pdf)

Im Projekt pyMeterBus wurde das Verhalten schon mal besprochen und ein Fix aufgezeigt:
[https://github.com/ganehag/pyMeterBus/issues/16](url)

Ich kann die Lösung leider nicht selbst implementieren, würde aber für Tests etc, entsprechend zuarbeiten.

Gruß Alex

**Comment by Apollon77** [comment]
Formal müsstest Du bitte das Issue in libmbus anlegen da, diese Library "Unter der Haube "genutzt wird. --> https://github.com/rscada/libmbus ... so in fact the question is if this library can already do that or not
