### ISSUE TITLE
NZR IC-M12 not recognized

### ISSUE THREAD

**Issue by UpAtGithub** [Apollon77/ioBroker.mbus#296]
Hi,
my request is related to the identification of the NZR IC-M12 12-channel Pulse Counter Device.

The communication via serial MBUS is established, the MBUS telegrams can be seen on the MBUS dataline (oscilloscope with serial decode). The communication tool from the manufacturer (windows app) can communicate correctly when connecting the RS-232 port  to the device chain.

The iobroker driver send "1040FD3D16" (hex) but no replies from the device can be detected.

It seems as if the detection process doesn't match the requirements of the device?

Perhaps there my be another way to establish an MBUS protocol to special unknown devices?

Thanks - Udo

**Comment by Apollon77** [comment]
In fact this is mbus protocol standard ...  The adapter uses libmbus. YOu can also try t ionstall libmbus on your linux box and use the command line tools from them.

Can you see in the manufacturer tools what they send out?

**Comment by Apollon77** [comment]
@UpAtGithub Any details to the questions I asked?
