### ISSUE TITLE
Ist der Adapter in Kombination mit einem RS232/Ethernet Wandler benutzbar?

### ISSUE THREAD

**Issue by houselightguy** [Apollon77/ioBroker.mbus#316]
Ich habe aktuell einen Stromzähler über M-Bus an einem Pegelwandler angeschlossen. Wenn ich diesen direkt mit einem USB-RS232 an dem Rechner anschließe kann ich den Zähler mit dem Adapter auslesen. Jetzt würde ich lieber das statt über USB über Netzwerk auszulesen. Wenn ich an meinem Windows Rechner das so verbinde funktioniert dies. Allerdings nicht über den Adapter in dem Iobroker. 
Ich habe bereits  versucht innerhalb des Adapters direkt die IP einzustellen und auch über netcat eine virtuelle Schnittstell zu erzeugen und diese in dem Adapter einzutragen. Leider aber auch ohne Erfolg.

**Comment by Apollon77** [comment]
Also der Adapter generell kann auch TCP. Es muss eine direkte TCP verbidnung sein zum Gerät, heisst wenn seriell gewandelt dann schon mit der korrekten Baudrate und so ... vllt mal mit socat testen  weil die kann ggf die seriellen Parameter korrekt setzen. Wie das genau mit einem RS232/Ethernet Wandler geht bin ich gerade überfragt ... Netzwerk an sich tut weil das die Tests vom Adapter auch testen!
