### ISSUE TITLE
Mbus USB Proxmox

### ISSUE THREAD

**Issue by ma-gu-16** [Apollon77/ioBroker.mbus#337]
Hi,

ich versuche meinen Stromzähler auszulesen. Der Mbus sollte aktiviert sein, laut Betreiber. 

Auf Anfrage hiess es das gErät ist der Master und ich benötige ein Mbus Slave. 

Wenn ich dies anschliesse und USB durchreiche, bekomm ich immer folgendes im Log: 

`
<html>
<body>

mbus.0 | 2023-10-17 16:09:50.217 | error | M-Bus Connection failed. Please check configuration.
-- | -- | -- | --
mbus.0 | 2023-10-17 16:09:50.215 | error | Error: No connection possible to MBus Serial port /dev/tty2
mbus.0 | 2023-10-17 16:09:50.214 | info | Initialize M-Bus Serial to /dev/tty2 with 2400baud
mbus.0 | 2023-10-17 16:09:50.214 | info | Default Update Interval: 3600
mbus.0 | 2023-10-17 16:09:50.194 | info | starting. Version 2.4.0 in /opt/iobroker/node_modules/iobroker.mbus, node: v16.18.1, js-controller: 5.0.12
host.ioBroker | 2023-10-17 16:09:47.574 | info | instance system.adapter.mbus.0 started with pid 1449

</body>
</html>
`

In der VM sollte das USB korrekt drin sein: 

![image](https://github.com/Apollon77/ioBroker.mbus/assets/22169074/1a4a1a9c-7152-4ded-a010-19ca4f937dde)

Ich habe alle möglichen Ports bereits versucht :( 
Kann mir jemand mit der Config helfen ? Die Baudrate sollte stimmen laut Datenblatt des Stromzählers. 

Danke

**Comment by Apollon77** [comment]
und ndu bist sicher das es tty2 ist ? Das glaube ich nicht ... USB ist meistens ttyUSB0 oder ttyA.... ... zeit mal die Port liste ... bzw zeig mal ls -la /dev/tty*

**Comment by ma-gu-16** [comment]
> Weiterhin wäre es komisch wenn das ein Master ist und du nen slave brauchst ... hätte ich noch nie gesehen. Ich tippe du brauchst den master

ich habe nun bei 3 firmen unabhängig gefragt, alle sagen ich benötige ein slave.  der slave hat auch ein TX led drauf , welche alle 5 sekunden scheinbar daten empfängt.

**Comment by ma-gu-16** [comment]
> und ndu bist sicher das es tty2 ist ? Das glaube ich nicht ... USB ist meistens ttyUSB0 oder ttyA.... ... zeit mal die Port liste ... bzw zeig mal ls -la /dev/tty*

die liste ist sehr lang. 
![image](https://github.com/Apollon77/ioBroker.mbus/assets/22169074/068ed0b1-31b7-4c5d-b06e-55dffda8267e)

lsusb: 

![image](https://github.com/Apollon77/ioBroker.mbus/assets/22169074/2b873ec9-c103-4eb0-9044-4436efff33c0)

tty2  ist mit sicherheit falsch :) aber wie gesagt, hab ich schon alles möglich ausprobierte und diverse pfade angegeben. es kommt nach einem neustart des adapters immer das gleiche problem.

**Comment by Apollon77** [comment]
try ls -la /dev/serial/by-id/

But in fact this mbus adapter interacts with an mbus aster ... I never tried it as a slave, so also no idea if that works at all

**Comment by ma-gu-16** [comment]
> try ls -la /dev/serial/by-id/
> 
> But in fact this mbus adapter interacts with an mbus aster ... I never tried it as a slave, so also no idea if that works at all

![image](https://github.com/Apollon77/ioBroker.mbus/assets/22169074/93ff771f-2305-49c5-82a7-e9aa36628684)

ja vermutlich wird das das problem sein... entweder ich kauf mir nochmal ein master für 30 dollar oder für 50 direkt etwas fertiges :) ich denke das slave funktioniert da er auch seit der freischaltung durch das e-werk schön blinkt und etwas empfängt. ich vermute das problem auch im adapter.  danke dir für deine hilfe :)

**Comment by Apollon77** [comment]
naja das erste ist das dein Linux System  das gerät nicht als device registriert ... es sei denn es bekommt ein generisches serielles interface. Klingt gerade eher nach einem Forum Thema um erstmkl das hinzubekommen :-)

**Comment by ma-gu-16** [comment]
> naja das erste ist das dein Linux System das gerät nicht als device registriert ... es sei denn es bekommt ein generisches serielles interface. Klingt gerade eher nach einem Forum Thema um erstmkl das hinzubekommen :-)

Ja denke auch. Vielleicht sind es auch nur paar zeilen Code, oder etwas mehr und ich muss das usb in der vm zum serial simulieren... für alles fehlt mir gerade die zeit :)  hab mir jetzt das geholt: https://gplug.ch/produkte/gplugm/ scheint out-of-the box zu gehen. dann sende ich mir die werte via mqtt.  Danke dir dennoch für deine Hilfe! TOP! Liebe Grüsse
