### ISSUE TITLE
Serial-Device Name editable custom

### ISSUE THREAD

**Issue by bahnuhr** [Apollon77/ioBroker.mbus#9]
Hallo Ingo,

wie im iobroker.forum besprochen hier nun das issue.

Bitte bei den Gerätenamen im Adapter ein "Anderes Device" einrichten, damit man selbst definierte Namen, z.B. /dev/lesewasser dort eintragen kann.

Danke im Voraus.

mfg
Dieter

**Comment by Apollon77** [comment]
Mindestens weitere Adapter:
- modbus
- mysensors
- zwave
- enocean
- cul
- maxcul
- rflink
- smartmeter

**Comment by Apollon77** [comment]
> Daher habe ich das serialport Paket modifiziert: Beim Sammeln der seriellen Geräte (unter Linux) werden ebenfalls Symlinks zu jeden Gerät mit eingesammelt.

schick denen doch mal nen PR! Da gibts auch ein Issue von mir zu dem Thema

**Comment by lvogt** [comment]
Habs gemacht - scheint aber niemanden zu interessen...

kurze Randbemerkung: bei "Tariff" fehlt das zweite F, sonst wird es eine deutsch-englisch Mischung...
https://github.com/Apollon77/ioBroker.mbus/blob/e7d4b27e2749818e52f7179f18beed9c5cf2c35c/main.js#L270

**Comment by Apollon77** [comment]
> Habs gemacht - scheint aber niemanden zu interessen...

it's trapped in my (to) long todo list ... so stay tuned please

**Comment by Apollon77** [comment]
PS: I only see PR for "update unchanged values" ... or am I blind?

**Comment by lvogt** [comment]
Sorry, I didn't make myself clear.

I created a PR at the node-serialport repository. And *there* has been no reaction at all...

**Comment by Apollon77** [comment]
aahh cool

**Comment by Apollon77** [comment]
Implemented now in smatermeter and mbus ... more to come step by step
