### ISSUE TITLE
Abfragezeit als Datenpunkt

### ISSUE THREAD

**Issue by AtomicIX** [Apollon77/ioBroker.mbus#98]
Ist es vielleicht möglich dort noch Änderungen vor zu nehmen? Ich würde es echt klasse finden, wenn man den Aktualisierung/Abfrage Intervall über einen Datenpunkt oder ähnliches laufen lassen könnte. Dann kann ich bei Bedarf z.B. alle 30sek Echtzeitdaten und wenn kein Bedarf mehr ist, alle 24h Daten abfragen und die Batterie im Wasserzähler zu schonen. Vielen dank jedenfalls. Tolle Arbeit.

**Comment by Apollon77** [comment]
The adapter altready offers an "updateNow" state that can be triggered to update the data outside of the normal interval. So your requirement can be achieved by a simple javascript that triggers the "extra updates" as needed
